import './reset.scss';
import './layout.scss';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='body'>
        <header>
          <nav className='navbar'>
            <a className='navbar__link' href="/rate">Currency Rate</a>
            <a className='navbar__link' href="/calculator">Exchange Calculator</a>
            <a className='navbar__link' href="/transaction">
              Transaction
            </a>
            <a className='navbar__link' href="/transactions">
              Transactions List
            </a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
